# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "462cb46cfb28d0dc078a3a6349f8edf5"
application_url = "https://temple-advertise-sport-reading.trycloudflare.com"
embedded = true
name = "module-a"
handle = "module-a"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://temple-advertise-sport-reading.trycloudflare.com/auth/callback",
  "https://temple-advertise-sport-reading.trycloudflare.com/auth/shopify/callback",
  "https://temple-advertise-sport-reading.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "quickstart-1add1160.myshopify.com"
automatically_update_urls_on_dev = true
